# Generated by Django 4.1.4 on 2022-12-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_commonpage_options_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(choices=[('педагог', 'педагог'), ('рабочий', 'рабочий'), ('служащий', 'служащий'), ('администрация', 'администрация')], default='педагог', max_length=255, verbose_name='Тип сотрудника')),
                ('pic', models.ImageField(upload_to='', verbose_name='Фотокарточка')),
                ('fio', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('birthdate', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('startworkdate', models.DateField(blank=True, verbose_name='Дата начала работы')),
                ('stud', models.TextField(blank=True, verbose_name='Образование')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('disc', models.TextField(blank=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
