# Generated by Django 4.1.4 on 2022-12-24 08:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_commonpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraf', wagtail.blocks.RichTextBlock(label='текстовый блок')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True, verbose_name='Содержание страницы'),
        ),
    ]
