# Generated by Django 4.1.4 on 2022-12-24 08:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_commonpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraf', wagtail.blocks.RichTextBlock(label='Текстовый блок')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение')), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображение'), label='Галерея изображений'))], blank=True, use_json_field=True, verbose_name='Содержание страницы'),
        ),
    ]
